-- Insert data into USERS table
INSERT INTO USERS (DISPLAYNAME, INTEREST_PEANUT, INTEREST_EGG, INTEREST_DAIRY) VALUES ('John Doe', true, false, true);
INSERT INTO USERS (DISPLAYNAME, INTEREST_PEANUT, INTEREST_EGG, INTEREST_DAIRY) VALUES ('Jane Smith', false, true, false);
--INSERT INTO USERS (DISPLAYNAME, INTEREST_PEANUT, INTEREST_EGG, INTEREST_DAIRY) VALUES ('Michael Brown', true, true, false);
--INSERT INTO USERS (DISPLAYNAME, INTEREST_PEANUT, INTEREST_EGG, INTEREST_DAIRY) VALUES ('Emily Davis', false, false, true);
--INSERT INTO USERS (DISPLAYNAME, INTEREST_PEANUT, INTEREST_EGG, INTEREST_DAIRY) VALUES ('David Wilson', true, false, false);
