-- src/main/resources/data.sql

-- Insert Users
INSERT INTO USERS (DISPLAYNAME, INTEREST_PEANUT, INTEREST_EGG, INTEREST_DAIRY) VALUES ('John Doe', true, false, true);
INSERT INTO USERS (DISPLAYNAME, INTEREST_PEANUT, INTEREST_EGG, INTEREST_DAIRY) VALUES ('Jane Smith', false, true, false);
INSERT INTO USERS (DISPLAYNAME, INTEREST_PEANUT, INTEREST_EGG, INTEREST_DAIRY) VALUES ('Alice Johnson', true, true, true);
INSERT INTO USERS (DISPLAYNAME, INTEREST_PEANUT, INTEREST_EGG, INTEREST_DAIRY) VALUES ('Bob Brown', false, false, false);
INSERT INTO USERS (DISPLAYNAME, INTEREST_PEANUT, INTEREST_EGG, INTEREST_DAIRY) VALUES ('Charlie Green', true, false, false);

-- Insert Restaurants
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Taste of Italy', '321 Vine St', 'Townsville', 'TS', '54321');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Spicy Bites', '654 Pepper St', 'Villageton', 'VT', '98765');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Burger Palace', '987 Beef St', 'Hamlet', 'HT', '54321');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Fish & Chips', '654 Cod St', 'Metropolis', 'MP', '98765');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Sushi Fusion', '789 Sushi St', 'Shire', 'SH', '54321');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Mediterranean Delights', '123 Olive St', 'Townsville', 'TS', '98765');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Thai Spice', '456 Chili St', 'Villageton', 'VT', '54321');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Steakhouse Grill', '789 Rib St', 'Hamlet', 'HT', '98765');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Vegan Garden', '101 Green St', 'Metropolis', 'MP', '54321');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Tex-Mex Fiesta', '202 Taco St', 'Shire', 'SH', '98765');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('French Bistro', '321 Baguette St', 'Townsville', 'TS', '13579');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Indian Spice', '654 Curry St', 'Villageton', 'VT', '24680');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Pizza Paradise', '987 Dough St', 'Hamlet', 'HT', '35791');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('BBQ Joint', '654 Smoke St', 'Metropolis', 'MP', '46802');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Noodle House', '789 Noodle St', 'Shire', 'SH', '57913');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Greek Taverna', '101 Gyro St', 'Townsville', 'TS', '68024');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Seafood Shack', '202 Fish St', 'Villageton', 'VT', '79135');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Breakfast Diner', '321 Pancake St', 'Hamlet', 'HT', '80246');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Smoothie Bar', '456 Fruit St', 'Metropolis', 'MP', '91357');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Dessert Haven', '789 Sweet St', 'Shire', 'SH', '02468');

-- Insert Restaurants
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Good Eats', '123 Main St', 'Townsville', 'TS', '12345');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Yummy Place', '456 Side St', 'Villageton', 'VT', '67890');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Tasty Corner', '789 Elm St', 'Hamlet', 'HT', '11223');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Savory Spot', '101 Pine St', 'Metropolis', 'MP', '33445');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Delicious Diner', '202 Oak St', 'Shire', 'SH', '55667');

-- Insert Restaurants with the same zipcode (12345) and different allergies
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Restaurant 1', '123 Main St', 'Townsville', 'TS', '12345');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Restaurant 2', '456 Side St', 'Villageton', 'VT', '12345');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Restaurant 3', '789 Elm St', 'Hamlet', 'HT', '12345');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Restaurant 4', '101 Pine St', 'Metropolis', 'MP', '12345');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Restaurant 5', '202 Oak St', 'Shire', 'SH', '12345');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Restaurant 6', '321 Elm St', 'Townsville', 'TS', '12345');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Restaurant 7', '654 Oak St', 'Villageton', 'VT', '12345');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Restaurant 8', '987 Main St', 'Hamlet', 'HT', '12345');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Restaurant 9', '345 Pine St', 'Metropolis', 'MP', '12345');
INSERT INTO RESTAURANT (NAME, ADDRESS, CITY, STATE, ZIPCODE) VALUES ('Restaurant 10', '678 Side St', 'Shire', 'SH', '12345');

-- Insert Restaurant Allergies (Adjust as needed based on your data)
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (1, 'PEANUT_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (1, 'DAIRY_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (2, 'EGG_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (3, 'PEANUT_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (4, 'DAIRY_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (4, 'EGG_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (5, 'PEANUT_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (5, 'DAIRY_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (5, 'EGG_FREE');

INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (6, 'PEANUT_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (6, 'DAIRY_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (7, 'EGG_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (8, 'PEANUT_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (9, 'DAIRY_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (9, 'EGG_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (10, 'PEANUT_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (10, 'DAIRY_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (10, 'EGG_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (11, 'PEANUT_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (12, 'EGG_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (13, 'DAIRY_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (14, 'PEANUT_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (15, 'DAIRY_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (15, 'EGG_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (16, 'PEANUT_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (16, 'DAIRY_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (17, 'EGG_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (18, 'PEANUT_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (18, 'DAIRY_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (18, 'EGG_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (19, 'PEANUT_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (19, 'DAIRY_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (19, 'EGG_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (35, 'PEANUT_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (21, 'DAIRY_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (21, 'EGG_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (21, 'PEANUT_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (26, 'DAIRY_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (26, 'EGG_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (26, 'PEANUT_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (30, 'DAIRY_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (30, 'EGG_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (30, 'PEANUT_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (32, 'DAIRY_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (32, 'EGG_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (32, 'PEANUT_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (34, 'EGG_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (34, 'DAIRY_FREE');
INSERT INTO RESTAURANT_ALLERGIES (restaurant_id, allergy) VALUES (31, 'PEANUT_FREE');

-- Insert Dining Reviews (Adjust as needed based on your data)
INSERT INTO DINING_REVIEWS (REVIEW_TITLE, USER_NAME, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, COMMENTARY, restaurant_id, user_id)
VALUES ('Great Place!', 'John Doe', 5, 4, 3, 'Really enjoyed the food, great for peanut allergy.', 1, 1);
INSERT INTO DINING_REVIEWS (REVIEW_TITLE, USER_NAME, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, COMMENTARY, restaurant_id, user_id)
VALUES ('Not Bad', 'Jane Smith', 3, 5, 2, 'Good food, but not great for dairy allergy.', 2, 2);
INSERT INTO DINING_REVIEWS (REVIEW_TITLE, USER_NAME, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, COMMENTARY, restaurant_id, user_id)
VALUES ('Excellent!', 'Alice Johnson', 4, 4, 4, 'Wonderful experience, safe for all allergies.', 3, 3);
INSERT INTO DINING_REVIEWS (REVIEW_TITLE, USER_NAME, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, COMMENTARY, restaurant_id, user_id)
VALUES ('Could be better', 'Bob Brown', 2, 3, 1, 'Food was okay, not very allergy-friendly.', 4, 4);
INSERT INTO DINING_REVIEWS (REVIEW_TITLE, USER_NAME, PEANUT_SCORE, EGG_SCORE, DAIRY_SCORE, COMMENTARY, restaurant_id, user_id)
VALUES ('Just Okay', 'Charlie Green', 3, 3, 3, 'Average experience, decent food.', 5, 5);